### ISSUE TITLE
bug: When entering my downloads folder

### ISSUE THREAD

**Issue by Arya-Elfren** [BrookJeynes/jido#5]
**Describe the bug**

If I enter my downloads folder (or any folder in it that causes it to analyse `~/downloads`) it exits with `error.FileNotFound`.

**To Reproduce**

I tried using rr to debug it, but I got no debug info and the tui operations kept interfering.

**Expected behavior**

Don't exit when entering a folder.

**Comment by Arya-Elfren** [comment]
I think it has to do with the call to `pdftotext`.

**Comment by Arya-Elfren** [comment]
After installing [poppler_utils](https://search.nixos.org/packages?channel=24.05&from=0&size=50&sort=relevance&type=packages&query=pdftotext) for pdftotext it's hanging (complete freeze, cpu at 0%) whilst converting a textbook to text.

**Comment by Arya-Elfren** [comment]
Yea, so if I don't have `pdftotext` available it crashes with `error.FileNotFound` when it tries to preview a pdf. but if I do and I go into `~/downloads` the top file alphabetically is too big and so it just hangs the program.

If I run `pdftotext` manually on the file it finishes very quickly though. A temporary fix might be to limit the `pdftotext` call to the first 10 pages?

**Comment by BrookJeynes** [comment]
Hey @Arya-Elfren, thanks for the bug report. I've noticed some issues with the pdf reader as well and I plan to fix this over this coming week/weekend. 

In regards to your debug information. You make a really good point. Currently the errors are very vague. I plan to add a `--debug` flag you can launch zfe with that will print out more information on errors that occur to std.err. This will mess with the tui layout so you will need to redirect errors to a file. I'll write up some info in the README once it's implemented.

**Comment by BrookJeynes** [comment]
Hey @Arya-Elfren, I've gone ahead and fixed the issue where attempting to view a pdf (with or without `pdftotext`) would freeze / crash zfe. Additionally, I've gone ahead and documented `pdftotext` as an optional dependency in the README under the "Optional Dependencies" heading.

You can download the latest version here https://github.com/BrookJeynes/zfe/releases/tag/v0.5.0


In regards to your debug comment, I've branched that off into another issue where you can keep track of it here - https://github.com/BrookJeynes/zfe/issues/6
